### ISSUE TITLE
Time related parsing issues

### ISSUE THREAD

**Issue by cactaceae21** [lnxg33k/MHA#12]
Errors in parsing time related entries in a header causing an exception.

Failing header entry:
```
Received: by mail.server.com with SMTP id thing0430p1iad2-24881-5C0E517F-22
        2018-12-10 11:43:59.610180118 +0000 UTC m=+555016.724468750
```

The portion following the time entry ` m=+555016.724468750` causes the error in server.py, line 134
"delay = org_time.second - next_time.second"

If the line was truncated after the timezone denomination (UTC in this case) when passing data to "python-dateutil" dependancy, the error no longer occurs.

**Comment by lnxg33k** [comment]
@cactaceae21 That last commit should fix your issue, feel free to re-open it incase it did not work.
