### ISSUE TITLE
Issue with time servers being out of alignment

### ISSUE THREAD

**Issue by randomaccess3** [lnxg33k/MHA#20]
There's a minor bug in the math if the timestamps for the received headers are out of order (likely the mailservers have different times set)

![image](https://user-images.githubusercontent.com/1241363/101297168-9e209380-387b-11eb-8ce8-fd25d10fafad.png)

It shows a 23 hour delay when it was a negative instead

**Comment by lnxg33k** [comment]
Please upload the headers somewhere for me to check. Feel free to re-open the issue
