### ISSUE TITLE
Unknown string format when parsing timestamp?

### ISSUE THREAD

**Issue by tomakey** [lnxg33k/MHA#5]
MHA hitting problem parsing this line (error 500):
Received: by server.domain.com id xx228x1xxxx0 for <first.last@domain2.com>; Sun, 1 Apr 2018 03:01:53 -0400 (envelope-from <bounce_yyyy-first.last=domain2.com@domain.com>)

Server side error messages:
raise ValueError("Unknown string format:", timestr)
ValueError: (u'Unknown string format:', 'Sun, 1 Apr 2018 03:01:53 -0400 (envelope-from <bounce_yyyy-first.last=domain2.com@domain.com>)')

**Comment by lnxg33k** [comment]
Can you please paste the headers you are trying to parse in here.
